 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:lts
     steps:
       - checkout
       - run: pwd
       - run: ls
       - run: npm i --no-save yarn
       - run: yarn
       - run: yarn test
