 version: 2
 jobs:
   build:
     docker:
       - image: levity/dapptools-node
     steps:
       - checkout
       - run: ./setup-env.sh
       - run: npm i --no-save yarn
       - run: yarn
       - run: yarn test
