 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:lts
     steps:
       - checkout
       - run: source ./scripts/install-dapptools.sh
       - run: npm i --no-save yarn
       - run: yarn
       - run: yarn test
