 version: 2
 jobs:
   build:
     docker:
       - image: nixorg/nix:circleci
     steps:
       - checkout
       - run: source ./scripts/install-ci-deps.sh
       - run: npm i --no-save yarn
       - run: yarn
       - run: yarn test
