version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm i yarn
      - run: yarn
      - run: |
          curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - run: |
          git clone https://github.com/makerdao/staxx.git
          cd staxx
          make dc-up
          make run-dev
          cd ..
          yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
